# $schema: https://docs.renovatebot.com/renovate-global-schema.json

version: 2
updates:
  - &a
    package-ecosystem: "npm"
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - Paul-16098

  - package-ecosystem: cargo
    <<: *a

  - package-ecosystem: github-actions
    <<: *a

  - package-ecosystem: gitsubmodule
    <<: *a

  - package-ecosystem: pip
    <<: *a

  - package-ecosystem: rust-toolchain
    <<: *a

  - package-ecosystem: uv
    <<: *a
