# $schema: https://docs.renovatebot.com/renovate-global-schema.json

version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - Paul-16098

  - package-ecosystem: cargo
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - Paul-16098

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - Paul-16098

  - package-ecosystem: gitsubmodule
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - Paul-16098

  - package-ecosystem: pip
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - Paul-16098

  - package-ecosystem: rust-toolchain
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - Paul-16098

  - package-ecosystem: uv
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - Paul-16098
